### ISSUE TITLE
Требования к игре 

### ISSUE THREAD

**Issue by Burize** [rustho/life#1]
Одно из требований: "У приложения должны быть кнопки "Начать заново", "Пауза" и инпуты "Ширина" и "Высота" - по unfocus инпутов поле должно перерендерится сразу же." 
У вас нет инпутов для ширины и высоты. Есть возможность задать количество клеток сразу для двух сторон (это не одно и тоже) + задается размер черех Alert, а не через инпут.

**Comment by rustho** [comment]
Add commit for issue #1
