### ISSUE TITLE
bracket styles

### ISSUE THREAD

**Issue by Zarwlar** [rustho/life#10]
Определиться со стилем отступов и придерживаться ему. Сейчас он меняется от места к месту. Мы используем стиль «K&R». Для того, чтобы не решать эту проблему "на глаз", лучше поставить линтер

**Comment by rustho** [comment]
Добавил tslint, но я чет не особо понял как он работает, по сути он должен с вебпаком ругаться, а ему норм

**Comment by rustho** [comment]
Всё, разобрался, вечером залью (%

**Comment by rustho** [comment]
Залил всё (: tslint классный
