### ISSUE TITLE
Сделать нормальный биндинг методов

### ISSUE THREAD

**Issue by Burize** [rustho/life#11]
```
const self = this;
        public startLife() {
        const self = this;
        if (this.timer === false) {
            this.timer = setInterval(() => self.nextState(self.board), this.speed);
        }
    }
```

`const self = this` - не лучший способ. По сути это костыль и сейчас без него легко можно обойтись. Существует несколько способ биндинга функций в js и их стоит изучить. 
В итоге должно получиться: `this.timer = setInterval(this.nextState(this.board), this.speed);` 
То есть в обработчик должна передаваться сама функция, а не функция, внутри которой идет вызов метода объекта self.

**Comment by rustho** [comment]
Хм,  я вот не нашёл этот пример, что ты скинул. 
По сути мы должны сделать универсальную функцию, которой можем забиндить любой контекст?

**Comment by Burize** [comment]
В целом да. Нужно прям погуглить по биндинг в JS. По сколько в чек листе на джуниора все равно есть вопрос про это 
`Какие есть способы навсегда привязать метод класса к его инстансу (чтобы this всегда был текущим экземпляром класса)?` 
,то лишним это в любом случае не будет.

**Comment by rustho** [comment]
Вот так пойдет? через биндинг в конструкторе? 
`constructor() {
        this._startLife = this._startLife.bind(this);
        this._stopLife = this._stopLife.bind(this);
}`

**Comment by Burize** [comment]
Ну вообще да это правильный подход, но его можно оптимизировать) Чтобы при создании нового метода не нужно было дописывать в конструкторе его биндинг. Например, написать функцию, которая будет вызываться в конструкторе и биндить все существующие методы класса. Там ничего сложного нет, но можно поискать и готовый вариант и разобраться как он работает.

**Comment by rustho** [comment]
Хм, попробовал вот так
`for (const name in this) {
            if (typeof(this[name]) === "function") {
                const method = this[name];
                this[name] = method.bind(this);
            }
        }`
но так не работает, пишет : 

> Property 'bind' does not exist on type 'this[keyof this]'.

нашел autobind он примерно также вроде работает, но у него какие-то траблы с тайпскриптом

**Comment by rustho** [comment]
Ну как-то так, конечно это дикий костыль, но по другому не хочет работать

**Comment by rustho** [comment]
К черту бинд! 
на самом деле нашел книжку каких-то стандартов, где вместо бинда предлагалось использовать стрелочные функции. 
Для тайпа - это маст хэв, потому что когда мы функцию оборачиваем в бинд, тайпинги функций уходят ко дну превращаясь в any, а при стрелочных функциях всё сохраняется, тем более всё это не выглядит ужасным, как гора биндов например.

**Comment by Znack** [comment]
В хендлеры событий из DOM-а можно {view: this} не передавать. У тебя методы вью и так забиндены к инстансу этой вьюхи, то есть ты там к this имеешь нормальный доступ. Так что убирай этот аргумент, а в методах спокойно юзай this, который инстанс вьюхи, а не  DOM-элемент
