### ISSUE TITLE
Убрать this из обработчиков.

### ISSUE THREAD

**Issue by Burize** [rustho/life#12]
```
$("#start").click(() => self._startLife());

public _startLife() {
        const startLife = new CustomEvent("startLife", { bubbles: true });
        this.publisher.notifySubscribers(startLife);
    }
```

В обработчиках событий не должно быть ссылок на контекст(this). Handler должен работать только с аргументами, которые передаются в объекте Event.

**Comment by rustho** [comment]
Хм, ты про обработчик событий имеешь ввиду функцию startlife?  
Или в целом при клике что исполняется?

**Comment by Burize** [comment]
Обработчик любого события: клик (по полю или по кнопке), ввод данных в инпут и тд.

**Comment by rustho** [comment]
Добавляем просто в евент дэйт ссылку на обьект который вызывает евент, норм?

**Comment by Burize** [comment]
Да, только вместо `$("#start").click({view: this}, (e) => e.data.view._startLife(e));` 
лучше `$("#start").click({view: this}, this._startLife);` 
А то у тебя вообще странно: при клике из объекта события берется ссылка на view, у него его метод и в него передается этот объект.

`Хм, ты про обработчик событий имеешь ввиду функцию startlife?
Или в целом при клике что исполняется?` 

Да имелось ввиду обработчик как функция, а не код внутри click().

**Comment by rustho** [comment]
Да, да, всё ок (: я поэтому и спрашивал (((:
