### ISSUE TITLE
Переписать всё на ES6 (2)

### ISSUE THREAD

**Issue by Burize** [rustho/life#13]
Как минимум контроллер не переписан. 

P. S. Не стоит закрывать issue - пусть висят. Не факт же, что ваши правки исправили проблему или требования.
P. S. S. Не очень понял про TypeSrcipt. Подразумевается, что он в этом проекте есть, но кроме loader для него и расширения .ts у файлов, я от него больше ничего не увидел: нет интерфейсов и типов у переменных.  Вообще его использование будет плюсом в этом задании, но не является обязательным.

**Comment by rustho** [comment]
Можно же заново открыть ишьюс
Типы у переменных есть, интерфейсов нет - это да.
