### ISSUE TITLE
MVC 

### ISSUE THREAD

**Issue by Burize** [rustho/life#14]
Не корректная реализация. Модель должна быть хранилищем данных и предоставлять методы для модификации/изменения этих данных. Никаких StartGame и StopGame в ней не должно быть. За это должен отвечать Контроллер. Так же как и взаимодействие между моделью и View должно осуществляться через его методы. 
При нынешней реализации как такового контроллера и нет, вместо него одна функция обработчик событий у view, а вся игровая логика реализована в модели.

**Comment by Burize** [comment]
Да и еще 

```
case "changeHeight":
                _view.changeSize(event.detail.width, event.detail.height);
                _model.changeQuantityCell(event.detail.width, event.detail.height);
                break;
```
Контроллер ничего не должен знать о event, о том,  что у него есть detail, и то что у detail есть width, height или еще что-то. У него должен быть свой метод, который принимает конкретные значение (ширины и высоты например, а не объект события), и их он уже обрабатывает. Это дает более низкую связанность. При нынешней реализации контроллер сильно зависит от того как реализовано событие.

**Comment by rustho** [comment]
ты имеешь ввиду оставить в обработчике только вызов методов? (: 
ну case "something":
    this.someMethod(event.detail.width);
    break;
....
someMethod (width){};

**Comment by Burize** [comment]
По-хорошему у контроллера должен быть собственный метод (например ChangeSize), который вызывается по событию вызванному у View. Этот метод должен принимать фактические параметры (размеры поля, а не событие). 
Да, на данном этапе это может показаться не логично, потому что метод контроллера будет просто вызывать метод модели, но если бы это был реальный проект, то при расширении проекта при изменении размеров поля могут возникнуть какие-либо проверки или дополнительные действия и тд. И при данной реализации весь этот дополнительный функционал для всех событий будет в 1 switch.
Так же, если в него будут передаваться фактические параметры (а не событие), то он будет более абстрагирован и его легко можно будет использовать с другим View, у которого объект события будет реализован по-другому. Сейчас контроллер для изменения размеров поля должен знать структуру объекта события, который ему передается.

**Comment by rustho** [comment]
Не, это всё понятно, почему и прочее, так и тестировать проще будет крайняк (:

**Comment by rustho** [comment]
Сделал

**Comment by Burize** [comment]
Осталось немного. Возможно я не правильно выразился, да теперь у контроллера есть свои методы, принимающие дискретные значения, но по прежнему в нем есть switch c `event.detail`. То есть контроллер все также должен знать структуру объекта события. Такого быть не должно.  
Контроллер должен просто подписывать свой метод на определенное событие у view. Как реализован функционал вызова этих событий он знать не должен. Событие где-то произошло - метод контроллера вызвался с переданными значениями и все. 

Посмотри как реализовано в  https://tproger.ru/translations/event-emitter-javascript/ (или его аналогах). Там реализация событий сделана как отдельный модуль/класс. Нужно сделать также.
