### ISSUE TITLE
Немного не работает ...

### ISSUE THREAD

**Issue by Burize** [rustho/life#15]
При начале игры не видно поля пока не задать размеры (ну это и раньше было...), и ошибка при клике по полю.

![2017-09-15 20-08-34](https://user-images.githubusercontent.com/22253666/30483630-bc679f4e-9a51-11e7-8c02-1a43f0f497ac.png)

**Comment by rustho** [comment]
исправил, а насчет того что не видно было поле, ну это однозначно фича была, нужно нажать было на старт или изменить размеры чтобы прорисовалось - так и планировалось ((:

**Comment by Burize** [comment]
Ну, да, теперь поле видно при загрузке страницы, но это (как я понял) потому что автоматические запускается сама игра. То есть вначале(после загрузки страницы) нужно нажать на паузу. Потом расставить клетки и снова нажать старт.  Хотелось бы, чтобы при загрузке было видно поле, чтобы понимать как оно выглядит и каких оно размеров и игра не была начата, чтобы можно было расставить клетки.

**Comment by rustho** [comment]
ну лан, как хочешь (: 
Ох уж эти заказчики (((:
