### ISSUE TITLE
Обращение к DOM в методах у View

### ISSUE THREAD

**Issue by Burize** [rustho/life#16]
Не заметил в прошлый раз. View это обычный объект/класс. Соответственно работать он должен со своими полями. 

```
public _changeHeight(e) {
        const height = parseInt($("#change_height").val().toString(), 10);
        const width = $("#field").width();
        const changeHeight = new CustomEvent("changeHeight", {
            bubbles: true,
            detail: { width, height },
        });
        e.data.view.publisher.notifySubscribers(changeHeight);
    }
```

Тут метод напрямую обращается к DOM: `$("#field").width();` .
Лучше если он будет работать с полями view, например, ` e.data.view.$field`.

Соответственно нужно в конструкторе инициализировать все поля для DOM элементов: `const $field = $("#field")` и уже в методах работать именно с полями класса, а не искать DOM элемент при каждом вызове метода. Ну и инициализацию полей нужно вынести в отдельный метод (так же как addEvents, только для полей)

**Comment by rustho** [comment]
О, да, точно, так должно быть намного лучше
