### ISSUE TITLE
Переписать всё на ES6

### ISSUE THREAD

**Issue by Zarwlar** [rustho/life#2]
В особенности операции над массивами, использовать классы

**Comment by rustho** [comment]
Попереписывал на typescript, классы сделал, операции над массивами ещё нет

**Comment by Zarwlar** [comment]
Также неплохо было бы использовать let, const, arrow function

**Comment by rustho** [comment]
Да, замутил лет, и стрелочкофункции (:

**Comment by rustho** [comment]
могу теперь и на es3 компилить! (:
