### ISSUE TITLE
При инициализации сделать проверку, что в this.$field лежит ровно один канвас

### ISSUE THREAD

**Issue by Znack** [rustho/life#36]
И грамотно обработать противные случаи

**Comment by rustho** [comment]
грамотно это как? Я просто заигнорил другой канвас и не стал с ним общаться. А что ты имеешь в виду? или нужно именно чтобы в это поле перешел только один элемент?

**Comment by Znack** [comment]
Лучше всегда действовать по принципу let it crash и если что-то идет не по плану, крашиться нафиг :)
так что под грамотной обработкой имеется ввиду сделать хорошие барьеры и проверки, и во всех неугодных случаях падать, в идеале кастомгными, понятными ошибками
