### ISSUE TITLE
Инпуты ничем не ограничены.

### ISSUE THREAD

**Issue by Geksanit** [rustho/life#47]
Инпуты ничем не ограничены. Обычно поле измеряется количеством ячеек.

**Comment by Geksanit** [comment]
Не ясно какой из инпутов задает высоту, а какой ширину.

**Comment by rustho** [comment]
Критичен ввод букв? Просто если критично, я могу сделать так чтобы после ввода в инпут надо было кнопку нажать и на буквы так будет проверяться

**Comment by Geksanit** [comment]
А по чему бы не использовать input(type=number) ?

**Comment by rustho** [comment]
Да-да, я сделал так, но "type = text" не убрал (:
