### ISSUE TITLE
Архитектура: обработчики событий.

### ISSUE THREAD

**Issue by Burize** [rustho/life#5]
```
document.getElementById('change_cell').onclick = function() {
            var n = parseInt(prompt('cells?',20)); 
            var changeQuantityCell = new CustomEvent('changeQuantityCell', {
                bubbles:true,
                detail:{n:n}
            })
            document.getElementById('field').dispatchEvent(changeQuantityCell);
        };
```

Обработчики для событий( и другие callback функции) лучше выносить в отдельные методы класса и потом их задавать для click, а не на прямую для DOM элемента. Если метод нужно будет переиспользовать в другом вместе в коде, то его придется задавать заново - то есть копипастить. + на него нельзя будет ссылаться во внешнем коде. Например при тестах если нам нужно будет проверить был ли этот обработчик вызван.

**Comment by rustho** [comment]
не знаю что делать с функцией клика, там просит координаты и прочее, что получаю из события клика

**Comment by Burize** [comment]
Не вижу проблемы. Точно также вынести как отдельную функцию, которая принимает на вход аргумент е.
