### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by kinda-neat** [rustho/life#50]
Project is running at http://localhost:8080/
По указанному адресу не игра, а папка, нужно еще перейти в public/ чтобы увидеть твое произведение, нужно это исправить :)

**Comment by rustho** [comment]
Погоди, т.е. это можно изменить? Оо Гдежтыраньшебыл ((((:

**Comment by rustho** [comment]
Я не знал о такой возможности... просто *facepalm*
